/* Mobile-first inpatient ophthalmology progress-note interface for index.html. */
(function(){
'use strict';

const STORAGE_KEY='cgmh_oph_progress_notes_v1';
const FIELDS=[
 {key:'visualAcuity',label:'Visual acuity',hint:'distance, correction, pinhole',v:['20/### with correction','20/### without correction; pinhole 20/###','Counting fingers at ### cm','Hand motion','Light perception with accurate projection','Light perception with inaccurate projection','No light perception','Unable to assess reliably']},
 {key:'pressure',label:'Intraocular pressure',hint:'value and instrument',v:['### mmHg by rebound tonometry','### mmHg by applanation tonometry','### mmHg by handheld applanation tonometry','Soft by digital palpation','Firm by digital palpation','Deferred because of suspected open-globe injury','Unable to measure']},
 {key:'pupil',label:'Pupil / afferent defect',hint:'size, reaction, asymmetry',v:['Round and reactive; no relative afferent pupillary defect','### mm in light and ### mm in dark; brisk reaction','Sluggish reaction; no relative afferent pupillary defect','Relative afferent pupillary defect present, grade ###','Pharmacologically dilated','Fixed and mid-dilated','Irregular pupil','Unable to assess']},
 {key:'motility',label:'Motility / alignment',hint:'movement, pain, diplopia',v:['Full extraocular movements; orthotropic in primary gaze','Extraocular movement limited in ### direction by ###','Pain with extraocular movement, greatest in ### direction','Diplopia in ### gaze','Globe displaced toward ###','Unable to assess']},
 {key:'lid',label:'Eyelid / periocular',hint:'edema, erythema, wound',v:['Normal eyelid position; no swelling or erythema','Mild eyelid edema','Moderate eyelid edema and erythema','Severe tense eyelid edema; unable to open voluntarily','Eyelid margin erythema with discharge on eyelashes','Entropion with lash-cornea touch','Lagophthalmos measuring ### mm','Periocular ecchymosis','Surgical wound clean, dry, and intact','Purulent drainage from ###']},
 {key:'conjunctiva',label:'Conjunctiva / sclera',hint:'injection, chemosis, wound',v:['Quiet conjunctiva; white sclera','Mild conjunctival injection','Moderate diffuse conjunctival injection with chemosis','Severe conjunctival injection and chemosis','Subconjunctival hemorrhage involving ###','Conjunctival epithelial defect measuring ### × ### mm','Pseudomembrane present over ###','Filtering bleb elevated and Seidel test negative','Filtering bleb avascular with suspected leak; Seidel test ###','Conjunctival wound secured with sutures in place']},
 {key:'cornea',label:'Cornea',hint:'clarity, defect, infiltrate, wound',v:['Clear cornea; no epithelial defect or infiltrate','Diffuse superficial punctate epithelial erosions','Epithelial defect measuring ### × ### mm at ###','Stromal infiltrate measuring ### × ### mm at ###, depth ###%','Epithelial defect ### × ### mm with infiltrate ### × ### mm','Corneal edema: ###','Descemet membrane folds: ###','Endothelial inflammatory deposits: ###','Corneal thinning to approximately ###% residual thickness','Corneal melt / ectasia at ###','Corneal graft clear; sutures intact','Corneal graft edema with rejection line at ###','Surgical wound secure; Seidel test negative','Surgical wound leak; Seidel test positive at ###','No view because of corneal opacity']},
 {key:'anteriorChamber',label:'Anterior chamber',hint:'depth, cells, flare, hypopyon',v:['Deep and quiet','Deep with cells ###+ and flare ###+','Shallow centrally and peripherally','Shallow peripherally; central depth ###','Hypopyon measuring ### mm','Hyphema occupying ###% of the anterior chamber','Fibrin present','Silicone oil / viscoelastic material suspected in anterior chamber','Flat anterior chamber','No view']},
 {key:'iris',label:'Iris',hint:'shape, ischemia, adhesions',v:['Normal iris architecture','Round pupil; no posterior synechiae','Posterior synechiae from ### to ### o’clock','Iris transillumination defects at ###','Iris neovascularization: ###','Iridodialysis from ### to ### o’clock','Iris tissue prolapse at ###','No view']},
 {key:'lens',label:'Lens',hint:'clarity, implant, capsule',v:['Clear crystalline lens','Nuclear sclerosis grade ###','Cortical lens opacity grade ###','Posterior subcapsular lens opacity grade ###','Posterior chamber intraocular lens centered in the capsular bag','Intraocular lens decentered toward ###','Aphakia','Traumatic lens opacity / capsule rupture at ###','Retained lens material: ###','No view']},
 {key:'vitreous',label:'Vitreous',hint:'cells, hemorrhage, gas/oil',v:['Clear vitreous','Vitreous cells ###+ and haze grade ###','Vitreous hemorrhage: mild / moderate / dense','Gas fill approximately ###%','Silicone oil fill approximately ###%','Posterior vitreous detachment present','No view; ultrasonography finding: ###']},
 {key:'disc',label:'Optic disc',hint:'color, margin, cup-to-disc ratio',v:['Pink optic disc with distinct margins; cup-to-disc ratio ###','Optic disc edema grade ###','Pale optic disc','Hyperemic optic disc','Peripapillary hemorrhage at ###','No view']},
 {key:'macula',label:'Macula',hint:'fluid, hemorrhage, status',v:['Flat macula with preserved foveal reflex','Macula attached','Macula detached','Macular edema: improved / stable / worsened','Subretinal fluid: improved / stable / worsened','Intraretinal fluid: improved / stable / worsened','Macular hemorrhage at ###','Macular scar / atrophy at ###','No view']},
 {key:'retina',label:'Retina / periphery',hint:'attachment, break, detachment',v:['Retina attached in all quadrants; no retinal break identified','Retinal detachment from ### to ### o’clock; macula on / off','Retinal break at ### o’clock with surrounding laser scars','Laser scars present from ### to ### o’clock','Scleral buckle indentation appropriate; retina attached','Choroidal detachment from ### to ### o’clock','Retinal hemorrhages at ###','No view; ultrasonography shows ###']},
 {key:'wound',label:'Wound / device',hint:'sutures, drain, implant',v:['No external wound or device','Corneal / scleral wound secured; sutures intact','Tube shunt well positioned; tube tip clear of cornea and iris','Filtering bleb formed; Seidel test negative','Bandage contact lens in place','Eye shield in place','Drain / packing at ### with output ###','Loose or broken suture at ### o’clock','Device position unable to assess']}
];

function mergeTemplates(base,custom){
 const byId=new Map(base.map(t=>[t.id,t]));
 (Array.isArray(custom)?custom:[]).forEach(t=>{if(t&&t.id)byId.set(t.id,t);});
 return [...byId.values()];
}

const EXAM_TEMPLATES=mergeTemplates([
 {id:'anterior-postop',group:'Postoperative monitoring',rank:1,common:'Very common',status:'Postoperative',title:'After cataract or anterior-segment surgery',f:{visualAcuity:'20/### with correction',pressure:'### mmHg by ###',pupil:'Round and reactive; no relative afferent pupillary defect',lid:'Mild eyelid edema',conjunctiva:'Mild conjunctival injection; surgical wound secured',cornea:'Surgical wound secure; Seidel test negative; corneal edema ###',anteriorChamber:'Deep with cells ###+ and flare ###+',iris:'Normal iris architecture',lens:'Posterior chamber intraocular lens centered in the capsular bag',vitreous:'Clear vitreous',disc:'Pink optic disc with distinct margins; cup-to-disc ratio ###',macula:'Flat macula',retina:'Retina attached in all quadrants; no retinal break identified',wound:'Corneal wound secured; sutures ###'}},
 {id:'retina-postop',group:'Postoperative monitoring',rank:2,common:'Common',status:'Postoperative',title:'After vitrectomy / retinal-detachment repair',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'###',lid:'Mild eyelid edema',conjunctiva:'Surgical wounds secured; conjunctival injection ###',cornea:'Clear cornea; epithelial defect ###',anteriorChamber:'Deep with cells ###+ and flare ###+',lens:'###',vitreous:'Gas / silicone oil fill approximately ###%',disc:'###',macula:'Macula attached / detached',retina:'Retina attached / detached from ### to ### o’clock; breaks ###; laser scars ###',wound:'Sclerotomy wounds secured; leakage ###'}},
 {id:'corneal-postop',group:'Postoperative monitoring',rank:3,common:'Common',status:'Postoperative',title:'After corneal transplantation or tectonic surgery',f:{visualAcuity:'###',pressure:'### mmHg by ###',lid:'Mild eyelid edema',conjunctiva:'Mild conjunctival injection; sutures ###',cornea:'Corneal graft clear / edematous; epithelial defect ### × ### mm; sutures intact / loose at ###',anteriorChamber:'Deep with cells ###+ and flare ###+; hypopyon ###',iris:'###',lens:'###',wound:'Graft-host junction secure; Seidel test negative / positive at ###'}},
 {id:'glaucoma-postop',group:'Postoperative monitoring',rank:4,common:'Common',status:'Postoperative',title:'After glaucoma filtration or drainage-device surgery',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'###',lid:'###',conjunctiva:'Filtering bleb / drainage-device plate appearance: ###; Seidel test ###',cornea:'Corneal edema ###; tube-cornea touch absent / present',anteriorChamber:'Deep / shallow; cells ###+; hyphema ###',iris:'###',lens:'###',wound:'Wound secured; tube position ###; ligature / stent status ###'}},
 {id:'keratitis',group:'Infection and ocular surface',rank:1,common:'Very common inpatient',status:'Urgent',title:'Microbial keratitis / corneal ulcer',f:{visualAcuity:'###',pressure:'### mmHg by ### / deferred',pupil:'###',lid:'Eyelid edema ### with discharge ###',conjunctiva:'Conjunctival injection ### with chemosis ###',cornea:'Epithelial defect ### × ### mm with stromal infiltrate ### × ### mm at ###, depth ###%; thinning ###%; endothelial plaque ###',anteriorChamber:'Deep with cells ###+ and flare ###+; hypopyon ### mm',iris:'### / no view',lens:'### / no view',vitreous:'### / no view; ultrasonography ###',retina:'### / no view'}},
 {id:'endophthalmitis',group:'Infection and ocular surface',rank:2,common:'Common emergency',status:'Urgent',title:'Suspected or treated endophthalmitis',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect ###',lid:'Eyelid edema and erythema ###',conjunctiva:'Severe conjunctival injection and chemosis',cornea:'Corneal edema ###; wound status ###',anteriorChamber:'Cells ###+ and flare ###+; fibrin ###; hypopyon ### mm',iris:'### / no view',lens:'### / no view',vitreous:'Vitreous cells ###+ and haze grade ### / no view',retina:'Fundus view ###; ultrasonography shows ###',wound:'Procedure wound / filtering bleb status ###; Seidel test ###'}},
 {id:'chemical',group:'Infection and ocular surface',rank:3,common:'Less common',status:'Urgent',title:'Chemical injury / severe ocular-surface injury',f:{visualAcuity:'###',pressure:'### mmHg by ### / deferred',pupil:'###',lid:'Eyelid burn / edema involving ###',conjunctiva:'Conjunctival epithelial defect involving ###%; ischemia involving ### clock hours; retained particulate matter ###',cornea:'Epithelial defect ### × ### mm; haze grade ###; limbal ischemia ### clock hours; thinning ###%',anteriorChamber:'Deep / shallow with cells ###+ and flare ###+',iris:'###',lens:'###'}},
 {id:'retinal-detachment',group:'Retina and posterior segment',rank:1,common:'Common admission',status:'Preoperative',title:'Retinal detachment before surgery',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect ###',conjunctiva:'Quiet conjunctiva; white sclera',cornea:'Clear cornea',anteriorChamber:'Deep and quiet',lens:'###',vitreous:'Posterior vitreous detachment / hemorrhage / pigment cells ###',disc:'Pink optic disc with distinct margins; cup-to-disc ratio ###',macula:'Macula attached / detached',retina:'Retinal detachment from ### to ### o’clock; retinal break(s) at ###; proliferative vitreoretinopathy grade ###'}},
 {id:'uveitis',group:'Inflammation and pressure',rank:1,common:'Common inpatient',status:'Urgent medical',title:'Severe anterior or panuveitis',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'###; posterior synechiae ###',conjunctiva:'Conjunctival injection ###',cornea:'Endothelial inflammatory deposits ###; corneal edema ###',anteriorChamber:'Cells ###+ and flare ###+; fibrin ###; hypopyon ### mm',iris:'Posterior synechiae from ### to ### o’clock; iris nodules ###',lens:'###',vitreous:'Vitreous cells ###+ and haze grade ###',disc:'###',macula:'Macular edema ###',retina:'Retinal vasculitis / chorioretinal lesions at ###'}},
 {id:'pressure',group:'Inflammation and pressure',rank:2,common:'Common emergency',status:'Urgent medical',title:'Acute intraocular-pressure crisis',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Fixed / sluggish and mid-dilated; relative afferent pupillary defect ###',lid:'###',conjunctiva:'Conjunctival injection ###',cornea:'Diffuse corneal edema ###',anteriorChamber:'Shallow centrally and peripherally / deep with inflammation ###',iris:'Iris bombe / neovascularization / normal architecture ###',lens:'###',disc:'Optic disc view ###; cup-to-disc ratio ###'}},
 {id:'orbital-cellulitis',group:'Orbit and trauma',rank:1,common:'Common orbital admission',status:'Urgent',title:'Orbital cellulitis / orbital abscess monitoring',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect absent / present grade ###',motility:'Pain with extraocular movement; limitation greatest in ###; diplopia ###',lid:'Severe eyelid edema and erythema ###',conjunctiva:'Conjunctival injection and chemosis ###',cornea:'Exposure-related epithelial defect ### / clear cornea',disc:'Optic disc edema / normal appearance / no view',retina:'Retinal perfusion and posterior pole appearance ###',wound:'Drain / sinus packing / operative wound status ###'}},
 {id:'open-globe',group:'Orbit and trauma',rank:2,common:'Less common',status:'Postoperative urgent',title:'Open-globe injury after primary repair',f:{visualAcuity:'###',pressure:'Deferred unless globe integrity confirmed by treating surgeon',pupil:'Shape ###; relative afferent pupillary defect ###',motility:'###',lid:'Periocular edema / laceration ###',conjunctiva:'Conjunctival wound secured; hemorrhage ###',cornea:'Corneal / scleral wound secured with sutures; Seidel test ###; epithelial defect ###',anteriorChamber:'Deep / shallow; hyphema ###%; inflammation ###',iris:'Iris defect / prolapse / repair status ###',lens:'Clear / traumatic opacity / aphakia / lens material ###',vitreous:'Vitreous hemorrhage ###',retina:'View ###; retinal/choroidal detachment or foreign-body status ###',wound:'Eye shield in place; repaired wound status ###'}},
 {id:'neuro',group:'Neuro-ophthalmic monitoring',rank:1,common:'Selective admission',status:'Medical',title:'Optic neuropathy / neuro-ophthalmic monitoring',f:{visualAcuity:'### with correction; pinhole ###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect grade ###',motility:'Extraocular movements ###; pain on movement ###; diplopia ###',lid:'No ptosis / ptosis measuring ### mm',conjunctiva:'Quiet conjunctiva; white sclera',cornea:'Clear cornea',anteriorChamber:'Deep and quiet',disc:'Optic disc edema grade ### / pallor ### / normal appearance',macula:'Flat macula',retina:'Retina attached; no retinal lesion explaining visual loss',wound:'Color vision ###; visual field ###; brightness perception ###'}},
 {id:'pkp-postop',group:'Corneal operations',rank:1,common:'Common corneal operation',status:'Postoperative',title:'Penetrating keratoplasty - early postoperative review',f:{visualAcuity:'### with correction; pinhole ###',pressure:'### mmHg by ###',pupil:'Round / irregular; relative afferent pupillary defect ###',lid:'Postoperative edema ###',conjunctiva:'Injection ###; conjunctival closure and exposed sutures ###',cornea:'Full-thickness graft clear / edematous; epithelial defect ### x ### mm; graft-host junction apposed; sutures intact / loose at ### o\'clock; Seidel test negative / positive at ###',anteriorChamber:'Deep / shallow with cells ###+ and flare ###+; fibrin / hypopyon ###',iris:'Iris-cornea touch / incarceration / synechiae ###',lens:'Crystalline lens / intraocular lens / aphakia: ###',vitreous:'View ###; inflammation / hemorrhage ###',disc:'View ###; disc ###',macula:'View ###; macula ###',retina:'View ###; retina attached / abnormality ###',wound:'Graft-host junction secure / leaking at ###; suture tension and exposure ###'}},
 {id:'endothelial-graft',group:'Corneal operations',rank:2,common:'Common corneal operation',status:'Postoperative',title:'DMEK / DSAEK endothelial keratoplasty',f:{visualAcuity:'### with correction; pinhole ###',pressure:'### mmHg by ###',pupil:'Round / mid-dilated; pupillary block absent / suspected',conjunctiva:'Injection ###; wounds ###',cornea:'Graft attached approximately ###%; detachment from ### to ### o\'clock involving central / peripheral graft; edema ###; Descemet folds ###; pachymetry ### micrometers',anteriorChamber:'Deep / shallow; air or gas bubble approximately ###%; cells ###+; peripheral iridotomy patent / blocked at ###',iris:'Peripheral iridotomy at ### o\'clock is patent / not patent; iris bombe absent / present',lens:'Intraocular lens position ### / phakic lens ###',wound:'Incisions secure; Seidel test negative / positive at ###; anterior-segment optical coherence tomography ###'}},
 {id:'dalk-postop',group:'Corneal operations',rank:3,common:'Established selective operation',status:'Postoperative',title:'Deep anterior lamellar keratoplasty',f:{visualAcuity:'### with correction; pinhole ###',pressure:'### mmHg by ###',conjunctiva:'Injection ###; sutures ###',cornea:'Lamellar graft clear / edematous; epithelial defect ### x ### mm; interface haze / fluid ###; Descemet membrane attached / detached; graft-host junction and sutures ###; Seidel test ###',anteriorChamber:'Single / double anterior chamber; central depth ###; cells ###+',iris:'###',lens:'###',wound:'Interface fluid / double chamber extent ###; anterior-segment optical coherence tomography ###'}},
 {id:'therapeutic-keratoplasty',group:'Corneal operations',rank:4,common:'Uncommon but time-critical',status:'Postoperative urgent',title:'Therapeutic or tectonic keratoplasty for infection / melt',f:{visualAcuity:'###',pressure:'### mmHg by ### / deferred',lid:'Edema and discharge ###',conjunctiva:'Injection / chemosis ###; scleral extension ###',cornea:'Therapeutic graft clear / edematous; epithelial defect ### x ### mm; recurrent infiltrate at ### measuring ### x ### mm; thinning ###%; graft-host junction ###; Seidel test ###',anteriorChamber:'Deep / shallow; cells ###+; fibrin ###; hypopyon ### mm',iris:'### / no view',lens:'### / no view',vitreous:'View ###; haze ###; ultrasonography ###',retina:'View ###; ultrasonography ###',wound:'Sutures intact / loose at ###; wound leak ###; microbiology ###'}},
 {id:'corneal-perforation',group:'Corneal operations',rank:5,common:'Uncommon emergency',status:'Perioperative urgent',title:'Corneal perforation after glue / membrane / patch graft',f:{visualAcuity:'###',pressure:'Deferred / ### mmHg after globe integrity confirmed',pupil:'Shape ###; iris plugging ###',conjunctiva:'Injection ###; adjacent scleral involvement ###',cornea:'Defect at ### measuring ### x ### mm; residual stromal thickness ###%; perforation / descemetocele ###; tissue adhesive position ###; bandage contact lens centered / displaced; Seidel test negative / positive at ###',anteriorChamber:'Deep / shallow / flat; re-formation ###; cells ###+; hypopyon ###',iris:'Iris prolapse / incarceration ###',lens:'###',wound:'Glue / amniotic membrane / patch graft intact ###; anterior-segment imaging ###'}},
 {id:'graft-rejection',group:'Corneal operations',rank:6,common:'Important graft complication',status:'Urgent medical',title:'Corneal graft rejection / graft failure',f:{visualAcuity:'### with correction; pinhole ###',pressure:'### mmHg by ###',conjunctiva:'Injection ###',cornea:'Graft edema ###; pachymetry ### micrometers; keratic precipitates ###; endothelial rejection line from ### to ###; epithelial rejection line / subepithelial infiltrates ###; sutures ###',anteriorChamber:'Deep with cells ###+ and flare ###+',iris:'Posterior synechiae / iris findings ###',lens:'###',wound:'Graft-host junction secure; Seidel test ###; comparison with prior graft clarity/thickness ###'}},
 {id:'ppv-rd-gas',group:'Retinal operations',rank:1,common:'Very common retinal operation',status:'Postoperative',title:'Vitrectomy with endolaser and gas for retinal detachment',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect ###',lid:'Postoperative edema ###',conjunctiva:'Injection ###; sclerotomy wounds closed / leaking ###',cornea:'Clear / edematous; epithelial defect ###',anteriorChamber:'Deep with cells ###+; hyphema / fibrin ###',lens:'Phakic / pseudophakic / aphakic; lens clarity ###',vitreous:'Gas fill approximately ###%; hemorrhage / inflammation ###',disc:'View through gas ###; disc ###',macula:'Macula attached / detached; optical coherence tomography ###',retina:'Retina attached in all quadrants / detached from ### to ### o\'clock; treated breaks at ###; laser uptake ###; residual subretinal fluid ###',wound:'Sclerotomies and conjunctiva secure; Seidel test ###'}},
 {id:'ppv-pvr-oil',group:'Retinal operations',rank:2,common:'Common complex retinal operation',status:'Postoperative',title:'Complex vitrectomy / retinectomy with silicone oil for PVR',f:{visualAcuity:'###',pressure:'### mmHg by ### / hypotony',pupil:'Relative afferent pupillary defect ###',cornea:'Clear / edema ###; oil-cornea touch absent / present',anteriorChamber:'Deep / shallow; cells ###+; silicone-oil droplets / oil fill in anterior chamber ###',lens:'Phakic / pseudophakic / aphakic ###',vitreous:'Silicone oil fill approximately ###%; emulsification ###; hemorrhage ###',disc:'View ###; perfusion ###',macula:'Attached / detached; subretinal or intraretinal fluid ###',retina:'Retina attached / detached at ###; retinectomy edge flat / elevated from ### to ###; proliferative vitreoretinopathy membranes ###; laser ###; retained perfluorocarbon liquid ###; choroidal detachment ###',wound:'Sclerotomies secure; oil leakage ###'}},
 {id:'scleral-buckle',group:'Retinal operations',rank:3,common:'Common established operation',status:'Postoperative',title:'Scleral buckle / cryotherapy for retinal detachment',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect ###',motility:'Extraocular movement limitation / diplopia ###',lid:'Postoperative edema / ecchymosis ###',conjunctiva:'Injection / chemosis ###; conjunctival closure ###; buckle exposure absent / present at ###',cornea:'Clear / epithelial defect ###',anteriorChamber:'Deep with cells ###+',lens:'###',vitreous:'Hemorrhage / pigment / gas ###',macula:'Macula attached / detached',retina:'Retina attached / detached from ### to ###; buckle height and support appropriate / inadequate at ###; break position relative to buckle ###; cryotherapy reaction ###; residual subretinal fluid ###; choroidal detachment ###',wound:'Buckle exposure/infection absent / suspected; conjunctival sutures ###'}},
 {id:'diabetic-trd',group:'Retinal operations',rank:4,common:'Common tertiary retinal operation',status:'Postoperative',title:'Vitrectomy for diabetic tractional retinal detachment / hemorrhage',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect ###',cornea:'Clear / edema ###',anteriorChamber:'Deep with cells ###+; hyphema ###',lens:'###',vitreous:'Clear / recurrent vitreous hemorrhage ###; gas / oil fill ###%',disc:'Neovascularization of disc absent / present ###',macula:'Macula attached / residual traction / edema ###; optical coherence tomography ###',retina:'Retina attached / residual tractional detachment at ###; residual fibrovascular membranes ###; retinal breaks ###; endolaser coverage ###; retinal / iris neovascularization ###',wound:'Sclerotomies secure; postoperative hemorrhage ###'}},
 {id:'macular-surgery',group:'Retinal operations',rank:5,common:'Common elective operation',status:'Postoperative',title:'Macular hole / epiretinal membrane peel',f:{visualAcuity:'###',pressure:'### mmHg by ###',cornea:'Clear / edema ###',anteriorChamber:'Deep with cells ###+',lens:'###',vitreous:'Gas fill approximately ###% / clear after vitrectomy',disc:'###',macula:'Macular hole open / closed / unable to assess; epiretinal membrane status ###; retinal edema ###; optical coherence tomography ###',retina:'Retina attached in all quadrants; iatrogenic / peripheral break absent / present at ###; laser ###',wound:'Sclerotomies secure; prescribed positioning ###'}},
 {id:'retina-infection-postop',group:'Retinal operations',rank:6,common:'Uncommon emergency operation',status:'Postoperative urgent',title:'Vitrectomy for endophthalmitis',f:{visualAcuity:'###',pressure:'### mmHg by ###',pupil:'Relative afferent pupillary defect ###',lid:'Edema / erythema ###',conjunctiva:'Injection / chemosis ###; wounds ###',cornea:'Edema ###; epithelial defect ###',anteriorChamber:'Cells ###+; fibrin ###; hypopyon ### mm',lens:'### / no view',vitreous:'Post-vitrectomy cavity clarity ###; residual debris / hemorrhage ###; tamponade ###',disc:'View ###; disc perfusion ###',macula:'View ###; macula ###',retina:'Retina attached / detached at ###; retinitis / necrosis / hemorrhage ###; ultrasonography ###',wound:'Sclerotomies secure; specimen stain/culture/polymerase chain reaction result ###'}},
 {id:'choroidal-drainage',group:'Retinal operations',rank:7,common:'Uncommon complex operation',status:'Postoperative urgent',title:'Drainage of choroidal detachment / suprachoroidal hemorrhage',f:{visualAcuity:'###',pressure:'### mmHg by ### / hypotony',pupil:'Relative afferent pupillary defect ###',cornea:'Clear / edema ###',anteriorChamber:'Deep / shallow / flat; re-formed after drainage ###',lens:'###',vitreous:'View ###; hemorrhage ###; tamponade ###',disc:'View ###; perfusion ###',macula:'Macula visible / obscured; status ###',retina:'Choroidal elevation from ### to ### o\'clock; kissing configuration absent / present; retinal attachment ###; drainage response ###; ultrasonography height and reflectivity ###',wound:'Drainage sites secure; leakage / hemorrhage ###'}},
],window.CGMH_PROGRESS_EXAM_TEMPLATES);

const PLAN_TEMPLATES=mergeTemplates([
 {id:'postop',group:'Postoperative',rank:1,common:'Very common',status:'Postoperative',title:'Routine postoperative inpatient monitoring',d:'- Check visual acuity and intraocular pressure at least ###.\n- Examine wound integrity, inflammation, hemorrhage, retinal attachment, and implant/device position as appropriate.\n- Review operation-specific imaging or laboratory results: ###.\n- Notify ophthalmology immediately for worsening pain, vision, pressure, wound leak, hemorrhage, infection, or neurologic symptoms.',t:'- Continue operation-specific medications exactly as prescribed; verify full drug name, concentration, route, frequency, laterality, and duration: ###.\n- Maintain eye shield, dressing, positioning, and activity restrictions as ordered: ###.\n- Provide pain and nausea control appropriate for this patient: ###.\n- Planned procedure or treatment change: ###.',e:'- Explained expected postoperative symptoms and individualized visual prognosis.\n- Reviewed medication technique, correct eye, schedule, positioning, lifting, water-contact, eye-rubbing, and travel restrictions.\n- Warning symptoms reviewed: worsening vision or pain, redness, discharge, flashes, floaters, visual-field loss, headache, nausea, or vomiting.',g:'- By ###, visual acuity is stable or improved from ### to ###.\n- Intraocular pressure remains between ### and ### mmHg.\n- Wound remains secure without leakage, infection, or progressive inflammation.\n- Patient/caregiver demonstrates the medication and care plan before discharge.'},
 {id:'preop',group:'Perioperative',rank:1,common:'Very common',status:'Preoperative',title:'Preoperative preparation for ophthalmic surgery',d:'- Confirm diagnosis, laterality, operative site, procedure, indication, urgency, and consent.\n- Repeat visual acuity, intraocular pressure, pupil/afferent defect, and operation-specific examination.\n- Review required imaging/measurements and patient-specific anesthesia investigations: ###.\n- Confirm allergies, anticoagulant/antiplatelet plan, fasting status, infection status, and relevant systemic disease.',t:'- Keep fasting from ### according to anesthesia instructions.\n- Continue or hold medications according to the documented perioperative plan: ###.\n- Administer preoperative eye medications only after confirming the order and correct eye: ###.\n- Planned operation: ###; eye: ###; anesthesia: ###; date/time: ###.',e:'- Discussed diagnosis, alternatives, material risks, expected benefit, limitations, and possible additional procedures.\n- Confirmed understanding of laterality, fasting, medication changes, positioning, recovery, and follow-up.\n- Questions answered; consent status: ###.',g:'- Before operating-room transfer, identity, procedure, eye, consent, allergies, fasting status, medication plan, investigations, and implant/equipment plan are verified.\n- No unresolved safety issue remains at surgical time-out.'},
 {id:'keratitis',group:'Infection',rank:1,common:'Very common inpatient',status:'Urgent medical',title:'Microbial keratitis / severe corneal ulcer',d:'- Serially measure epithelial defect, infiltrate, depth, thinning, anterior-chamber inflammation, and hypopyon; obtain photographs at ###.\n- Obtain corneal scraping for stain, culture, and susceptibility testing when indicated; record prior antimicrobial exposure.\n- Review contact-lens, trauma, water, soil/vegetable matter, surgery, steroid, and immune-status history.\n- Perform ultrasonography if the fundus cannot be visualized and globe integrity permits: ###.',t:'- Administer topical antimicrobial treatment per cornea specialist and local protocol; verify agent, concentration, schedule, laterality, and interval: ###.\n- Adjust treatment to clinical response and microbiology.\n- Additional cycloplegia, pressure treatment, systemic therapy, anti-collagenase measures, protection, or surgery: ###.\n- Escalate urgently for thinning, perforation, scleral extension, endophthalmitis, or deterioration.',e:'- Explained that frequent drops, including overnight dosing when ordered, are time-critical.\n- Demonstrated hand hygiene, drop separation, correct laterality, and avoidance of bottle-tip contact.\n- Reviewed warning symptoms and avoidance of contact lenses and unsupervised anesthetic/steroid drops.',g:'- By ### hours, epithelial defect decreases from ### × ### mm to ### × ### mm and infiltrate is stable or smaller.\n- Thinning does not progress beyond ###%.\n- Hypopyon/inflammation improves from ### to ###.\n- Prescribed administration schedule is completed without missed doses.'},
 {id:'endophthalmitis',group:'Infection',rank:2,common:'Common emergency',status:'Urgent procedure',title:'Suspected or treated endophthalmitis',d:'- Serially document visual acuity, pupil/afferent defect, pressure, wound/bleb status, hypopyon, vitreous haze, retinal view, and pain.\n- Obtain aqueous/vitreous specimens for stain, bacterial/fungal culture, and susceptibility testing as directed.\n- Perform ultrasonography when the posterior segment cannot be seen and globe integrity permits.\n- Determine source; for suspected endogenous infection, coordinate systemic-source evaluation and cultures.',t:'- Treat as an ophthalmic emergency; do not delay senior ophthalmology/retina review.\n- Intravitreal antimicrobial treatment and vitrectomy timing are determined by the treating team and local protocol: ###.\n- Adjunctive topical, cycloplegic, pressure, systemic antimicrobial, and anti-inflammatory treatment: ###.\n- Reassess promptly and escalate for deterioration.',e:'- Explained the vision-threatening infection, uncertain prognosis, urgent procedures, and possible repeated injection or surgery.\n- Reviewed symptoms requiring immediate notification and emphasized treatment timing.\n- Patient/family discussion and decision-maker: ###.',g:'- Intravitreal treatment/operation is completed by ###.\n- By ### hours, pain, hypopyon, inflammation, and vitreous haze are stable or improved.\n- Culture results are reviewed and treatment revised by ###.\n- Globe integrity is preserved without retinal detachment or uncontrolled pressure.'},
 {id:'retina-preop',group:'Retina',rank:1,common:'Common admission',status:'Preoperative urgent',title:'Retinal detachment awaiting repair',d:'- Document visual acuity, afferent defect, pressure, lens, vitreous hemorrhage, detachment extent, breaks, macular status, proliferative vitreoretinopathy, and fellow eye.\n- Obtain retinal imaging/ultrasonography as indicated: ###.\n- Confirm symptom onset, last intake, prior retinal procedures, antithrombotic use, and anesthesia fitness.\n- Repeat examination urgently for progression.',t:'- Protect activity and position according to the retina surgeon’s instructions: ###.\n- Maintain fasting and preoperative preparation as ordered.\n- Planned procedure, eye, anesthesia, and timing: ###.\n- Continue/hold ocular and systemic medications per perioperative plan: ###.',e:'- Explained macular status, urgency, alternatives, prognosis, recurrence risk, and possible further procedures.\n- Reviewed tamponade positioning and travel/anesthesia restrictions if gas may be used.\n- Report progression of field loss, central vision loss, floaters/flashes, pain, headache, nausea, or vomiting immediately.',g:'- Surgery occurs by ### unless status or informed decision changes.\n- Macular status and visual field remain stable before surgery.\n- Laterality, consent, fasting, positioning, and anesthesia preparation are verified.'},
 {id:'retina-postop',group:'Retina',rank:2,common:'Common',status:'Postoperative',title:'After vitrectomy / retinal-detachment repair',d:'- Check visual acuity, pressure, wounds, anterior-chamber reaction, lens, tamponade fill, retinal attachment, macula, and choroid.\n- Confirm tamponade agent and percentage fill: ###.\n- Monitor for pressure elevation, hypotony, hemorrhage, infection, recurrent detachment, and positioning complications.',t:'- Continue postoperative drops with full drug name, concentration, frequency, laterality, and taper: ###.\n- Maintain prescribed positioning: ### for ### hours/day until ###.\n- Eye shield and activity restrictions: ###.\n- Pressure treatment, symptom control, or additional procedure: ###.',e:'- Reviewed positioning with return demonstration.\n- If gas is present: no air travel, high altitude, or nitrous-oxide anesthesia until confirmed resolved.\n- Reviewed warning symptoms and expected temporary visual limitation from tamponade.',g:'- Retina remains attached and tamponade position appropriate on ###.\n- Pressure remains between ### and ### mmHg.\n- Patient demonstrates positioning and states gas restrictions before discharge.'},
 {id:'pressure',group:'Pressure and inflammation',rank:1,common:'Common emergency',status:'Urgent medical',title:'Acute intraocular-pressure elevation',d:'- Recheck pressure at ### intervals and document method.\n- Record visual acuity, pupil/afferent defect, corneal edema, chamber depth/inflammation, angle status when safe, lens, optic nerve, pain, headache, nausea, and vomiting.\n- Identify mechanism: angle closure, inflammation, steroid response, retained material, silicone oil, pupillary block, neovascularization, hemorrhage, or device.\n- Check patient-specific contraindications and safety parameters before systemic treatment.',t:'- Administer pressure-lowering treatment according to mechanism and order; verify contraindications and complete medication details: ###.\n- Treat the cause and arrange laser/surgery if indicated: ###.\n- Monitor systemic symptoms and adverse effects; escalate for worsening pressure, pain, vision, or systemic status.',e:'- Explained mechanism, optic-nerve risk, treatment options, medication precautions, and possible urgent laser/surgery.\n- Report worsening vision, halos, pain, headache, nausea, vomiting, weakness, breathing difficulty, or confusion immediately.',g:'- Pressure decreases from ### to below ### mmHg by ### without important systemic adverse effects.\n- Pain/nausea improves from ###/10 to ###/10.\n- Corneal clarity and visual acuity are stable or improved; definitive treatment is planned by ###.'},
 {id:'uveitis',group:'Pressure and inflammation',rank:2,common:'Common inpatient',status:'Urgent medical',title:'Severe uveitis / scleritis requiring admission',d:'- Serially grade chamber cells/flare, hypopyon, vitreous haze, retinal/choroidal lesions, vasculitis, macular edema, optic disc, visual acuity, and pressure.\n- Evaluate infection risk before immunosuppression; obtain phenotype-directed laboratory, imaging, and fluid studies: ###.\n- Coordinate relevant medical consultations.',t:'- Begin or adjust anti-inflammatory, antimicrobial, cycloplegic, pressure, and immunomodulatory treatment only after required infection assessment: ###.\n- Verify medication details and monitor ocular/systemic toxicity.\n- Escalate for worsening vision, inflammation, pressure, retinal lesion, or systemic involvement.',e:'- Explained diagnostic uncertainty, infection-versus-inflammation distinction, treatment risks, recurrence, and follow-up.\n- Reviewed medication precautions and warning symptoms: ###.',g:'- By ###, chamber cells improve from ###+ to ###+, vitreous haze from ### to ###, and pain from ###/10 to ###/10.\n- Pressure remains between ### and ### mmHg.\n- Required investigations are collected and a treatment pathway documented by ###.'},
 {id:'orbital',group:'Orbit and trauma',rank:1,common:'Common orbital admission',status:'Urgent medical/surgical',title:'Orbital cellulitis / abscess',d:'- Serially record visual acuity, color/brightness, pupil/afferent defect, pressure, proptosis, displacement, retropulsion, motility, pain, diplopia, optic disc, exposure, fever, and neurologic status.\n- Obtain contrast-enhanced orbital/sinus and intracranial imaging as indicated.\n- Review blood tests and obtain relevant cultures.\n- Coordinate ear-nose-throat, infectious disease, medical/pediatric, and neurosurgical teams as appropriate.',t:'- Continue broad-spectrum intravenous antimicrobial treatment per local protocol and patient factors: ###.\n- Treat sinus source and protect exposed cornea.\n- Urgent drainage/orbitotomy/sinus procedure for optic compromise, abscess, intracranial extension, deterioration, or inadequate response: ###.\n- Escalate immediately for visual or neurologic change.',e:'- Explained risk of visual loss and intracranial spread, frequent examinations, intravenous treatment, multidisciplinary care, and possible drainage.\n- Report any visual, pain, diplopia, headache, vomiting, or neurologic change immediately.',g:'- Visual acuity, color/brightness, and pupil response remain stable at each ###-hour assessment.\n- Fever, pain, swelling, proptosis, and movement restriction improve by ### hours.\n- Imaging/culture results are reviewed and plan updated by ###.'},
 {id:'open-globe',group:'Orbit and trauma',rank:2,common:'Less common',status:'Emergency perioperative',title:'Open-globe injury / intraocular foreign body',d:'- Document mechanism, time, contaminant, tetanus status, visual acuity, pupil/afferent defect, wound zone, tissue prolapse, lens injury, hyphema, posterior injury, and foreign-body suspicion without pressure on the eye.\n- Avoid pressure measurement, gonioscopy, eyelid manipulation, and ultrasonography until considered safe.\n- Obtain thin-slice orbital computed tomography; avoid magnetic resonance imaging if metallic foreign body is possible.\n- Confirm fasting, allergies, antimicrobial timing, tetanus plan, and anesthesia fitness.',t:'- Place rigid eye shield; avoid patch pressure, rubbing, bending/straining, and oral intake.\n- Provide antiemetic, analgesic, antimicrobial, and tetanus management per protocol: ###.\n- Arrange urgent repair/foreign-body management: eye ###, zone ###, procedure ###, time ###.',e:'- Explained severe injury, uncertain prognosis, infection/detachment risk, urgent surgery, and possible staged procedures.\n- Reinforced no intake, no pressure on eye, and immediate reporting of nausea, vomiting, pain, or visual change.',g:'- Eye remains shielded without added pressure or Valsalva.\n- Antimicrobial/tetanus and operative preparation completed by ###.\n- Primary repair/definitive procedure occurs by ### with postoperative structural and infection plan.'},
 {id:'neuro',group:'Neuro-ophthalmic',rank:1,common:'Selective admission',status:'Urgent diagnostic',title:'Acute optic neuropathy / neuro-ophthalmic visual loss',d:'- Serially document corrected visual acuity, color vision, brightness, pupil/afferent defect, field, motility/alignment, eyelid, pain, optic disc, macula, and retina.\n- Obtain brain/orbit vascular or contrast imaging according to suspected diagnosis and urgency: ###.\n- Obtain targeted inflammatory, infectious, vascular, toxic, nutritional, and demyelinating studies: ###.\n- Coordinate relevant specialties.',t:'- Treat the confirmed or strongly suspected cause according to specialist consensus; verify medication/procedure details and contraindications: ###.\n- Do not allow empiric treatment to delay time-critical vascular, compressive, infectious, or intracranial evaluation.\n- Provide visual safety and systemic monitoring.',e:'- Explained working diagnosis, uncertainty, imaging/testing urgency, treatment risks, and visual prognosis.\n- Report further visual loss, field defect, diplopia, weakness, numbness, speech change, severe headache, vomiting, or altered consciousness.',g:'- Time-critical imaging and consultations completed by ###.\n- Visual acuity, color, field, and pupil findings stable or improved at ###.\n- Cause-directed treatment and follow-up plan documented before discharge.'},
 {id:'pkp-plan',group:'Corneal operations',rank:1,common:'Common corneal operation',status:'Postoperative',title:'Penetrating keratoplasty postoperative care',d:'- Serially document corrected visual acuity, intraocular pressure, epithelial defect, graft clarity and thickness, graft-host junction, suture integrity, Seidel test, anterior-chamber inflammation, lens status, and posterior segment view.\n- Compare graft edema and pachymetry with the prior examination: ###.\n- Assess urgently for wound leak, infection, rejection, pressure elevation, choroidal detachment, or retinal detachment when clinically suspected.',t:'- Continue the corneal surgeon\'s postoperative antimicrobial and anti-inflammatory regimen; verify complete drug, concentration, laterality, frequency, and taper: ###.\n- Maintain eye shield, wound precautions, activity restrictions, and surface lubrication as ordered: ###.\n- Address loose/broken sutures, wound leak, uncontrolled pressure, infection, or graft complication with the treating surgeon: ###.',e:'- Reviewed strict drop technique, eye protection, no rubbing, and individualized activity/water restrictions.\n- Report sudden visual decline, increasing pain/redness, discharge, photophobia, trauma, or a broken/loose suture immediately.\n- Explained the need for prolonged graft and pressure surveillance.',g:'- Graft remains structurally secure with negative Seidel test and no progressive epithelial defect by ###.\n- Graft clarity/edema and anterior-chamber inflammation are stable or improved at ###.\n- Intraocular pressure remains between ### and ### mmHg.\n- Patient demonstrates the medication and eye-protection plan before discharge.'},
 {id:'endothelial-plan',group:'Corneal operations',rank:2,common:'Common corneal operation',status:'Postoperative',title:'DMEK / DSAEK endothelial graft care',d:'- Document graft attachment percentage and detachment location, corneal edema/pachymetry, air or gas fill, chamber depth, peripheral iridotomy patency, pupil, inflammation, wound leakage, and intraocular pressure.\n- Obtain anterior-segment optical coherence tomography when attachment is uncertain or to follow detachment: ###.\n- Screen promptly for pupillary block, pressure elevation, graft displacement, infection, and primary graft failure.',t:'- Maintain the surgeon-prescribed supine or other positioning schedule: ### for ### hours/day through ###.\n- Continue postoperative eye medications with complete details: ###.\n- Urgent pressure treatment, bubble adjustment, rebubbling, or other intervention is determined by graft position, central involvement, symptoms, and surgeon assessment: ###.',e:'- Demonstrated required positioning and reviewed safe breaks.\n- Report pain, headache, nausea, worsening vision/redness, or inability to maintain positioning immediately.\n- If an intraocular gas bubble is present, follow the documented altitude, air-travel, and anesthesia restrictions.',g:'- Graft attachment improves or remains at least ###% by ###.\n- Central corneal edema/pachymetry improves from ### to ### by ###.\n- Peripheral iridotomy remains patent, chamber remains formed, and pressure remains between ### and ### mmHg.'},
 {id:'therapeutic-graft-plan',group:'Corneal operations',rank:3,common:'Uncommon but time-critical',status:'Postoperative urgent',title:'Therapeutic keratoplasty / corneal perforation care',d:'- Measure epithelial defect, recurrent infiltrate, graft-host junction, thinning, Seidel test, chamber depth, hypopyon, scleral extension, and posterior-segment status at each review.\n- Follow operative tissue, corneal scraping, and other microbiology/histopathology results: ###.\n- Use ultrasonography when the fundus cannot be seen and globe integrity permits: ###.',t:'- Continue cause-directed antimicrobial treatment and postoperative medications per cornea and infectious-disease guidance; verify complete details and toxicities: ###.\n- Maintain rigid protection or shield and avoid pressure, rubbing, bending, or straining as ordered.\n- Escalate immediately for leak, recurrent melt/infiltrate, graft infection, flat chamber, endophthalmitis, or posterior complication; planned procedure: ###.',e:'- Explained that the operation may control infection or preserve globe integrity without guaranteeing useful vision.\n- Reviewed time-critical medication administration, eye protection, and warning symptoms.\n- Patient/caregiver demonstrates the treatment schedule before discharge.',g:'- Seidel test remains negative and chamber remains formed at each ###-hour assessment.\n- Infiltrate, epithelial defect, thinning, and hypopyon are stable or improved by ###.\n- Microbiology results are reviewed and treatment updated by ###.'},
 {id:'ppv-rd-plan',group:'Retinal operations',rank:1,common:'Very common retinal operation',status:'Postoperative',title:'Vitrectomy / retinal-detachment repair with gas',d:'- Serially document visual acuity, pressure, sclerotomy integrity, anterior chamber, lens, gas fill, retinal attachment, break/laser status, macula, residual subretinal fluid, hemorrhage, and choroidal detachment.\n- Confirm the exact tamponade agent, concentration, and operation-specific positioning order: ###.\n- Assess promptly for recurrent detachment, pressure elevation, pupillary block, hypotony, endophthalmitis, hemorrhage, or retinal incarceration.',t:'- Continue postoperative medication regimen with complete drug details: ###.\n- Maintain prescribed positioning: ### for ### hours/day until ###; protect pressure points and the fellow eye.\n- Maintain eye shield and activity restrictions: ###.\n- Treat pressure/hypotony or arrange re-intervention according to the retina surgeon: ###.',e:'- Patient/caregiver demonstrates positioning and medication technique.\n- No air travel, high altitude, or nitrous-oxide anesthesia while intraocular gas remains; carry gas identification information when provided.\n- Report a new curtain, worsening vision or pain, redness/discharge, headache, nausea, or vomiting immediately.',g:'- Retina and macula remain attached / improve as specified at ###.\n- Gas position supports the intended break and pressure remains between ### and ### mmHg.\n- Patient accurately demonstrates positioning and states all gas restrictions before discharge.'},
 {id:'pvr-oil-plan',group:'Retinal operations',rank:2,common:'Common complex retinal operation',status:'Postoperative',title:'Complex PVR / retinectomy with silicone oil',d:'- Document pressure and hypotony, cornea, anterior-chamber oil, lens, oil fill/emulsification, retinal attachment, retinectomy edge, residual membranes, laser, macula, choroid, and retained perfluorocarbon liquid.\n- Obtain retinal imaging or ultrasonography according to view and clinical question: ###.\n- Monitor for recurrent proliferative vitreoretinopathy, oil migration, pressure elevation, keratopathy, inflammation, hemorrhage, and recurrent detachment.',t:'- Continue the retina surgeon\'s postoperative medication and positioning regimen: ###.\n- Manage pressure, hypotony, inflammation, and corneal protection according to mechanism: ###.\n- Planned oil retention/removal assessment and possible further retinal surgery: ###.',e:'- Explained the complex course, recurrence risk, temporary visual limitation, possible multiple operations, and need for pressure/cornea surveillance.\n- Reviewed positioning, medication, activity, and individualized travel/anesthesia instructions.\n- Report worsening vision, field loss, pain, redness, discharge, headache, nausea, or vomiting immediately.',g:'- Retina remains attached and retinectomy edge remains flat at ###.\n- Oil fill and position are appropriate without progressive anterior migration.\n- Pressure remains between ### and ### mmHg and no progressive corneal decompensation occurs before discharge.'},
 {id:'buckle-plan',group:'Retinal operations',rank:3,common:'Common established operation',status:'Postoperative',title:'Scleral buckle / cryotherapy postoperative care',d:'- Document visual acuity, pressure, pupil, motility/diplopia, anterior segment, buckle height and break support, retinal and macular attachment, residual subretinal fluid, hemorrhage, cryotherapy response, and choroidal detachment.\n- Inspect conjunctival closure and buckle exposure/infection: ###.\n- Reassess urgently for progressive detachment, buckle malposition, pressure change, infection, anterior-segment ischemia, or severe motility limitation.',t:'- Continue postoperative drops, analgesia, antiemetic therapy, shield, and activity restrictions with complete details: ###.\n- Position according to the retina surgeon if gas or break location requires it: ###.\n- Additional drainage, buckle revision, vitrectomy, or pressure treatment: ###.',e:'- Explained expected swelling/discomfort and temporary refractive or motility change.\n- Reviewed medication, shield, activity, positioning if applicable, and warning symptoms.\n- Report a new curtain, worsening vision/pain, increasing swelling/redness, discharge, diplopia, headache, nausea, or vomiting.',g:'- Break remains supported and retina/macula remain attached at ###.\n- Conjunctiva remains closed without buckle exposure or infection.\n- Pain, swelling, motility, and pressure are stable or improved by ###.'},
 {id:'macular-plan',group:'Retinal operations',rank:4,common:'Common elective operation',status:'Postoperative',title:'Macular hole / epiretinal membrane surgery',d:'- Document visual acuity, pressure, wounds, lens, gas fill, retinal attachment, peripheral breaks/laser, and macular status.\n- Obtain macular optical coherence tomography when timing and media permit: ###.\n- Screen for pressure elevation, retinal break/detachment, endophthalmitis, hemorrhage, and positioning complications.',t:'- Continue prescribed postoperative medications and shield/activity restrictions: ###.\n- Maintain face-down or other prescribed positioning: ### for ### hours/day until ###, with pressure-point and respiratory precautions.\n- Manage pressure or other postoperative complication according to the retina surgeon: ###.',e:'- Demonstrated positioning and safe breaks; discussed equipment and caregiver support.\n- If gas is present: no air travel, high altitude, or nitrous-oxide anesthesia until confirmed absorbed.\n- Explained that anatomical closure and visual recovery occur on different timelines.',g:'- Retina remains attached and macular hole/retinal contour is stable or improved on assessment at ###.\n- Pressure remains between ### and ### mmHg.\n- Patient demonstrates positioning and states gas precautions before discharge.'},
],window.CGMH_PROGRESS_PLAN_TEMPLATES);

const PLAN_BANK_STORAGE_KEY='cgmh_progress_plan_bank_v1';
const PLAN_DEFAULTS=JSON.parse(JSON.stringify(PLAN_TEMPLATES));
try{
 const savedPlanBank=JSON.parse(localStorage.getItem(PLAN_BANK_STORAGE_KEY)||'null');
 if(Array.isArray(savedPlanBank)&&savedPlanBank.length)PLAN_TEMPLATES.splice(0,PLAN_TEMPLATES.length,...savedPlanBank);
}catch(e){}
// Expose the live list so Template Bank edits immediately reach the Plan toolbox.
window.CGMH_PROGRESS_PLAN_BANK=PLAN_TEMPLATES;
window.CGMH_PROGRESS_PLAN_DEFAULTS=PLAN_DEFAULTS;
window.pnSetPlanBank=function(list){
 if(!Array.isArray(list))return false;
 const clean=list.filter(t=>t&&t.id&&t.title).map(t=>JSON.parse(JSON.stringify(t)));
 PLAN_TEMPLATES.splice(0,PLAN_TEMPLATES.length,...clean);
 window.CGMH_PROGRESS_PLAN_BANK=PLAN_TEMPLATES;
 try{localStorage.setItem(PLAN_BANK_STORAGE_KEY,JSON.stringify(PLAN_TEMPLATES));}catch(e){return false;}
 return true;
};

let patients=[],currentId=null,laterality='OU',templateMode='exam',descriptorField=null,descriptorTarget='OD';
const $=id=>document.getElementById(id);
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function now(){return new Date().toISOString();}
function blank(lot){return{id:'pn-'+Date.now()+'-'+Math.random().toString(36).slice(2,7),lot,created:now(),updated:now(),laterality:'OU',clinicalSummary:'',exam:{},examFree:'',diagnostic:'',therapeutic:'',education:'',goal:''};}
function current(){return patients.find(p=>p.id===currentId)||null;}
function loadStore(){try{const a=JSON.parse(localStorage.getItem(STORAGE_KEY)||'[]');patients=Array.isArray(a)?a:[];}catch(e){patients=[];}}
function persist(){try{localStorage.setItem(STORAGE_KEY,JSON.stringify(patients));}catch(e){alert('Local saving failed. Export the notes before leaving this page.');}}
function buildRows(){$('pn-exam-fields').innerHTML=FIELDS.map(f=>'<div class="pn-exam-row"><button type="button" class="pn-field-btn" onclick="pnOpenDescriptor(\''+f.key+'\')">'+esc(f.label)+'<small>'+esc(f.hint)+'</small></button><textarea id="pn-'+f.key+'-OD" aria-label="'+esc(f.label)+' right eye"></textarea><textarea id="pn-'+f.key+'-OS" aria-label="'+esc(f.label)+' left eye"></textarea></div>').join('');}

window.pnOpenNewPatient=function(){if(currentId)saveCurrent(false);const i=$('pn-new-lot');i.value='11J';$('pn-patient-dialog').showModal();setTimeout(()=>{i.focus();i.setSelectionRange(i.value.length,i.value.length);},30);};
window.pnCreatePatient=function(){const lot=$('pn-new-lot').value.trim();if(!lot){$('pn-new-lot').focus();return;}const p=blank(lot);patients.unshift(p);currentId=p.id;laterality='OU';persist();$('pn-patient-dialog').close();loadEditor(p);renderCards();$('pn-editor').scrollIntoView({behavior:'smooth',block:'start'});};
function syncEyeAccess(){
 ['OD','OS'].forEach(eye=>{
   const enabled=laterality==='OU'||laterality===eye;
   FIELDS.forEach(f=>{const el=$('pn-'+f.key+'-'+eye);if(el){el.disabled=!enabled;el.setAttribute('aria-disabled',String(!enabled));}});
 });
 const heads=document.querySelectorAll('.pn-exam-head span');
 if(heads[1])heads[1].classList.toggle('pn-eye-muted',laterality==='OS');
 if(heads[2])heads[2].classList.toggle('pn-eye-muted',laterality==='OD');
}
window.pnSetLaterality=function(eye){laterality=eye;document.querySelectorAll('[data-pn-eye]').forEach(b=>b.classList.toggle('on',b.dataset.pnEye===eye));syncEyeAccess();};
function loadEditor(p){currentId=p.id;laterality=p.laterality||'OU';$('pn-empty-editor').hidden=true;$('pn-editor').hidden=false;$('pn-current-lot').textContent=p.lot;$('pn-clinical-summary').value=p.clinicalSummary||'';window.pnSetLaterality(laterality);FIELDS.forEach(f=>['OD','OS'].forEach(eye=>{$('pn-'+f.key+'-'+eye).value=((p.exam||{})[f.key]||{})[eye]||'';}));$('pn-exam-free').value=p.examFree||'';['diagnostic','therapeutic','education','goal'].forEach(k=>$('pn-'+k).value=p[k]||'');renderCards();}
function collect(p){p.laterality=laterality;p.clinicalSummary=$('pn-clinical-summary').value.trim();p.exam=p.exam||{};FIELDS.forEach(f=>p.exam[f.key]={OD:$('pn-'+f.key+'-OD').value.trim(),OS:$('pn-'+f.key+'-OS').value.trim()});p.examFree=$('pn-exam-free').value.trim();['diagnostic','therapeutic','education','goal'].forEach(k=>p[k]=$('pn-'+k).value.trim());p.updated=now();return p;}
let summarySaveTimer;
window.pnSummaryChanged=function(value){const p=current();if(!p)return;p.clinicalSummary=String(value||'').trim();renderCards();clearTimeout(summarySaveTimer);summarySaveTimer=setTimeout(persist,250);};
function saveCurrent(message){const p=current();if(!p)return;collect(p);persist();renderCards();if(message!==false&&window.toast)toast('Progress note saved');}
window.pnSaveAndRefresh=function(){if(!current())return;saveCurrent(true);currentId=null;$('pn-editor').hidden=true;$('pn-empty-editor').hidden=false;$('pn-empty-editor').textContent='Progress note saved. Add another patient or select a saved patient card.';renderCards();$('pn-card-strip').scrollIntoView({behavior:'smooth',block:'nearest'});};
window.pnEdit=function(id){if(currentId)saveCurrent(false);const p=patients.find(x=>x.id===id);if(p){loadEditor(p);$('pn-editor').scrollIntoView({behavior:'smooth',block:'start'});}};
window.pnDelete=function(id){const p=patients.find(x=>x.id===id);if(!p||!confirm('Delete the saved progress note for Patient Lot# '+p.lot+'? This cannot be undone.'))return;patients=patients.filter(x=>x.id!==id);if(currentId===id){currentId=null;$('pn-editor').hidden=true;$('pn-empty-editor').hidden=false;}persist();renderCards();if(window.toast)toast('Saved note deleted');};
window.pnClearAll=function(){
 if(!patients.length)return;
 const count=patients.length;
 if(!confirm('Clear all '+count+' saved patient progress '+(count===1?'note':'notes')+'? This cannot be undone. Export first if a backup is needed.'))return;
 patients=[];currentId=null;persist();
 $('pn-editor').hidden=true;$('pn-empty-editor').hidden=false;
 $('pn-empty-editor').textContent='All saved patient progress notes were cleared. Add a new patient to continue.';
 renderCards();if(window.toast)toast('All saved patients cleared');
};

window.pnOpenDescriptor=function(key){const f=FIELDS.find(x=>x.key===key);if(!f)return;descriptorField=key;if(laterality==='OD'||laterality==='OS')descriptorTarget=laterality;else{const od=$('pn-'+key+'-OD').value.trim(),os=$('pn-'+key+'-OS').value.trim();descriptorTarget=!od?'OD':(!os?'OS':'OD');}$('pn-descriptor-title').textContent=f.label+' finding';$('pn-descriptor-help').textContent='For both-eye notes, the first selection fills OD (right eye); reopening this toolbox then fills OS (left eye). You may override the target.';renderTarget();$('pn-descriptor-list').innerHTML=f.v.map((v,i)=>'<button type="button" class="pn-descriptor" onclick="pnApplyDescriptor('+i+')">'+esc(v)+'</button>').join('');$('pn-descriptor-dialog').showModal();};
function renderTarget(){$('pn-descriptor-target').innerHTML=['OD','OS','OU'].map(e=>'<button type="button" class="'+(descriptorTarget===e?'on':'')+'" onclick="pnSetDescriptorTarget(\''+e+'\')">'+(e==='OU'?'OU · both':e==='OD'?'OD · right':'OS · left')+'</button>').join('');}
window.pnSetDescriptorTarget=function(e){descriptorTarget=e;renderTarget();};
window.pnApplyDescriptor=function(i){const f=FIELDS.find(x=>x.key===descriptorField);if(!f||!f.v[i])return;(descriptorTarget==='OU'?['OD','OS']:[descriptorTarget]).forEach(eye=>{const el=$('pn-'+f.key+'-'+eye);el.value=el.value.trim()?el.value.trim()+'; '+f.v[i]:f.v[i];});$('pn-descriptor-dialog').close();};

window.pnOpenTemplateTool=function(mode){templateMode=mode;$('pn-template-search').value='';$('pn-template-title').textContent=mode==='exam'?'Examination templates':'Hospitalization plan templates';$('pn-template-help').textContent=mode==='exam'?'Templates fill empty examination fields for the selected laterality. Existing findings are preserved. Confirm every ### before signing.':'Templates append editable Diagnostic, Therapeutic, Patient education, and Measurable goal text. Confirm every ###.';renderTemplates('');$('pn-template-dialog').showModal();setTimeout(()=>$('pn-template-search').focus(),30);};
function badgeClass(s){s=String(s).toLowerCase();if(s.includes('urgent')||s.includes('emergency'))return'urgent';if(s.includes('postoperative'))return'postop';if(s.includes('preoperative'))return'preop';return'common';}
function renderTemplates(q){const src=templateMode==='exam'?EXAM_TEMPLATES:PLAN_TEMPLATES;q=String(q||'').trim().toLowerCase();const rows=src.filter(t=>!q||[t.title,t.group,t.common,t.status].join(' ').toLowerCase().includes(q));let html='';[...new Set(rows.map(t=>t.group))].forEach(group=>{const grouped=rows.filter(t=>t.group===group).sort((a,b)=>a.rank-b.rank);html+='<section class="pn-template-section"><div class="pn-template-group"><span>'+esc(group)+'</span><small>'+grouped.length+' '+(grouped.length===1?'template':'templates')+'</small></div><div class="pn-template-grid">';grouped.forEach(t=>html+='<button type="button" class="pn-template-card" onclick="pnApplyTemplate(\''+t.id+'\')"><strong>#'+t.rank+' · '+esc(t.title)+'</strong><span class="meta"><span class="pn-badge '+badgeClass(t.common)+'">'+esc(t.common)+'</span><span class="pn-badge '+badgeClass(t.status)+'">'+esc(t.status)+'</span></span></button>');html+='</div></section>';});$('pn-template-list').innerHTML=html||'<div class="pn-empty-editor">No templates match that search.</div>';}
window.pnRenderTemplateTool=renderTemplates;
window.pnApplyTemplate=function(id){if(templateMode==='exam'){const t=EXAM_TEMPLATES.find(x=>x.id===id);if(!t)return;const eyes=laterality==='OU'?['OD','OS']:[laterality];Object.entries(t.f).forEach(([field,value])=>eyes.forEach(eye=>{const el=$('pn-'+field+'-'+eye);if(el&&!el.value.trim())el.value=value;}));if(window.toast)toast('Examination template added');}else{const t=PLAN_TEMPLATES.find(x=>x.id===id);if(!t)return;const map={diagnostic:'d',therapeutic:'t',education:'e',goal:'g'};Object.entries(map).forEach(([field,key])=>{const el=$('pn-'+field);el.value=el.value.trim()?el.value.trim()+'\n'+t[key]:t[key];});if(window.toast)toast('Hospitalization plan template added');}$('pn-template-dialog').close();};
window.pnClearPlan=function(){const a=['diagnostic','therapeutic','education','goal'].map(k=>$('pn-'+k));if(a.some(x=>x.value.trim())&&!confirm('Clear all four Plan fields?'))return;a.forEach(x=>x.value='');};

function eyeLabel(e){return e==='OD'?'OD (right eye)':e==='OS'?'OS (left eye)':'OU (both eyes: OD and OS)';}
const EXPORT_LABELS={visualAcuity:'VA',pressure:'IOP',pupil:'Pupil',motility:'EOM',lid:'Lid',conjunctiva:'CONJ',cornea:'K',anteriorChamber:'AC',iris:'Iris',lens:'Lens',vitreous:'Vit',wound:'Wound'};
function wrapWords(value,width){
 const result=[];
 String(value||'').split(/\r?\n/).forEach(paragraph=>{
   let words=paragraph.trim().split(/\s+/).filter(Boolean),line='';
   if(!words.length){result.push('');return;}
   words.forEach(word=>{
     while(word.length>width){if(line){result.push(line);line='';}result.push(word.slice(0,width));word=word.slice(width);}
     if(!line)line=word;else if(line.length+1+word.length<=width)line+=' '+word;else{result.push(line);line=word;}
   });
   if(line)result.push(line);
 });
 return result.length?result:[''];
}
function fixedExamRow(label,od,os,scope){
 const labelWidth=8,colWidth=37,gap='  ';
 if(scope==='OD'||scope==='OS'){
   const val=scope==='OD'?od:os,lines=wrapWords(val,colWidth*2+2);
   return lines.map((line,i)=>(i===0?(label+':').padEnd(labelWidth):''.padEnd(labelWidth))+line).join('\n');
 }
 const left=wrapWords(od,colWidth),right=wrapWords(os,colWidth),count=Math.max(left.length,right.length),rows=[];
 for(let i=0;i<count;i++)rows.push((i===0?(label+':').padEnd(labelWidth):''.padEnd(labelWidth))+(left[i]||'').padEnd(colWidth)+gap+(right[i]||''));
 return rows.join('\n').replace(/\s+$/gm,'');
}
function fundusText(p,eye){
 const exam=p.exam||{},parts=['disc','macula','retina'].map(k=>((exam[k]||{})[eye]||'').trim()).filter(Boolean);
 return parts.join('; ');
}
function wrappedFundus(prefix,text){
 const width=76,lines=wrapWords(text,width-prefix.length);
 return lines.map((line,i)=>(i===0?prefix:' '.repeat(prefix.length))+line).join('\n');
}
function format(p){
 const scope=p.laterality||'OU',out=['███ ['+p.lot+'] ██████████████████████','','[Ophthalmological examination]'];
 if(p.clinicalSummary)out.splice(2,0,'Reason for admission / working impression:',p.clinicalSummary,'');
 if(scope==='OU')out.push(''.padEnd(8)+'OD'.padEnd(37)+'  OS');else out.push(''.padEnd(8)+eyeLabel(scope));
 Object.keys(EXPORT_LABELS).forEach(key=>{const r=(p.exam||{})[key]||{},od=scope==='OS'?'':r.OD||'',os=scope==='OD'?'':r.OS||'';if(od||os)out.push(fixedExamRow(EXPORT_LABELS[key],od,os,scope));});
 const odFundus=scope==='OS'?'':fundusText(p,'OD'),osFundus=scope==='OD'?'':fundusText(p,'OS');
 if(odFundus)out.push(wrappedFundus("F'd (OD) ",odFundus));
 if(osFundus)out.push(wrappedFundus(scope==='OU'?'    (OS) ':"F'd (OS) ",osFundus));
 if(p.examFree)out.push('Additional: '+p.examFree);
 out.push('','[Plan]','[Diagnostic]',p.diagnostic||'','[Therapeutic]',p.therapeutic||'','[Patient education]',p.education||'','[Measurable goal]',p.goal||'');
 return out.join('\n').replace(/\n{3,}/g,'\n\n').trim();
}
function time(s){try{return new Date(s).toLocaleString([],{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'});}catch(e){return'';}}
function preview(p){return(p.diagnostic||p.therapeutic||p.examFree||Object.values(p.exam||{}).map(v=>v.OD||v.OS||'').find(Boolean)||'Blank draft — select Edit to continue.').replace(/\n/g,' ');}
function renderCards(){$('pn-card-strip').innerHTML=patients.map(p=>'<article class="pn-patient-card '+(p.id===currentId?'current':'')+'"><div class="pn-card-top"><span class="pn-card-lot">'+esc(p.lot)+'</span><span class="pn-badge">'+esc(p.laterality||'OU')+'</span></div><div class="pn-card-time">Updated '+esc(time(p.updated))+'</div><div class="pn-card-summary"><strong>Reason / impression</strong>'+esc(p.clinicalSummary||'Not entered yet')+'</div><div class="pn-card-preview">'+esc(preview(p))+'</div><div class="pn-card-actions"><button type="button" onclick="pnEdit(\''+p.id+'\')">Edit</button><button type="button" onclick="pnCopyPatient(\''+p.id+'\')">Copy</button><button type="button" class="danger" onclick="pnDelete(\''+p.id+'\')">Delete</button></div></article>').join('')||'<div class="pn-empty-editor" style="grid-column:1/-1">No saved patients yet.</div>';$('pn-export').disabled=!patients.length;const clear=$('pn-clear-all');if(clear)clear.disabled=!patients.length;}
window.pnCopyPatient=async function(id){const p=patients.find(x=>x.id===id);if(!p)return;try{await navigator.clipboard.writeText(format(p));}catch(e){const ta=document.createElement('textarea');ta.value=format(p);document.body.appendChild(ta);ta.select();document.execCommand('copy');ta.remove();}if(window.toast)toast('Progress note copied');};
window.pnExportAll=function(){if(!patients.length)return;if(currentId)saveCurrent(false);const blob=new Blob(['\ufeff'+patients.map(format).join('\n\n')],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='ophthalmology-progress-notes-'+new Date().toISOString().slice(0,10)+'.txt';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000);if(window.toast)toast('TXT export created');};

const IMPORT_KEYS=Object.fromEntries(Object.entries(EXPORT_LABELS).map(([key,label])=>[label.toLowerCase(),key]));
function importedSection(text,start,end){const a=text.indexOf(start);if(a<0)return'';const from=a+start.length,b=end?text.indexOf(end,from):-1;return text.slice(from,b<0?text.length:b).trim();}
function importFundus(p,eye,text){const parts=String(text||'').split(/;\s*/).filter(Boolean);if(parts[0])p.exam.disc[eye]=parts.shift();if(parts[0])p.exam.macula[eye]=parts.shift();if(parts.length)p.exam.retina[eye]=parts.join('; ');}
function parseImportedPatient(lot,body){
  const p=blank(lot),examText=importedSection(body,'[Ophthalmological examination]','[Plan]'),lines=examText.replace(/^\s*\n/,'').split('\n');
  p.clinicalSummary=importedSection(body,'Reason for admission / working impression:','[Ophthalmological examination]');
 const header=lines.shift()||'';p.laterality=/\bOD\b.*\bOS\b/.test(header)?'OU':(/\bOS\b/.test(header)?'OS':'OD');p.exam={};FIELDS.forEach(f=>p.exam[f.key]={OD:'',OS:''});
 let active=null,fundusEye=null,fundus={OD:'',OS:''};
 const add=(key,eye,value)=>{value=String(value||'').trim();if(!value)return;p.exam[key][eye]+=(p.exam[key][eye]?' ':'')+value;};
 lines.forEach(raw=>{
   if(!raw.trim())return;
   let m=raw.match(/^F'd \((OD|OS)\)\s*(.*)$/);if(!m)m=raw.match(/^\s+\((OS)\)\s*(.*)$/);
   if(m){fundusEye=m[1];fundus[fundusEye]=m[2].trim();active={type:'fundus'};return;}
   if(raw.startsWith('Additional:')){p.examFree=raw.slice(11).trim();active={type:'additional'};fundusEye=null;return;}
   m=raw.match(/^([^:]{1,7}):\s*/);
   if(m){const key=IMPORT_KEYS[m[1].trim().toLowerCase()];if(!key){active=null;return;}active={type:'row',key};fundusEye=null;if(p.laterality==='OU'){add(key,'OD',raw.slice(8,45));add(key,'OS',raw.slice(47));}else add(key,p.laterality,raw.slice(8));return;}
   if(active&&active.type==='fundus'&&fundusEye){fundus[fundusEye]+=(fundus[fundusEye]?' ':'')+raw.trim();return;}
   if(active&&active.type==='additional'){p.examFree+=(p.examFree?' ':'')+raw.trim();return;}
   if(active&&active.type==='row'){if(p.laterality==='OU'){add(active.key,'OD',raw.slice(8,45));add(active.key,'OS',raw.slice(47));}else add(active.key,p.laterality,raw.slice(8));}
 });
 importFundus(p,'OD',fundus.OD);importFundus(p,'OS',fundus.OS);
 p.diagnostic=importedSection(body,'[Diagnostic]','[Therapeutic]');p.therapeutic=importedSection(body,'[Therapeutic]','[Patient education]');p.education=importedSection(body,'[Patient education]','[Measurable goal]');p.goal=importedSection(body,'[Measurable goal]',null);p.updated=now();return p;
}
function parseProgressTxt(text){
 text=String(text||'').replace(/^\ufeff/,'').replace(/\r\n?/g,'\n');const markers=[...text.matchAll(/^███ \[([^\]\n]+)\] █+/gm)],out=[];
 markers.forEach((m,i)=>{const start=m.index+m[0].length,end=i+1<markers.length?markers[i+1].index:text.length;out.push(parseImportedPatient(m[1].trim(),text.slice(start,end).trim()));});return out;
}
window.pnImportTxt=async function(input){
 const file=input&&input.files&&input.files[0];if(!file)return;
 try{
   if(file.size>2*1024*1024)throw new Error('The TXT file is larger than 2 MB.');
   const imported=parseProgressTxt(await file.text());if(!imported.length)throw new Error('No CGMH ophthalmology progress-note divider was found.');
   if(currentId)saveCurrent(false);const duplicateLots=imported.map(p=>p.lot).filter(lot=>patients.some(old=>old.lot===lot));
   if(duplicateLots.length&&!confirm('Replace existing saved card(s) with the same Patient Lot#?\n\n'+[...new Set(duplicateLots)].join(', ')))return;
   const lots=new Set(imported.map(p=>p.lot));patients=[...imported,...patients.filter(p=>!lots.has(p.lot))];currentId=null;$('pn-editor').hidden=true;$('pn-empty-editor').hidden=false;$('pn-empty-editor').textContent=imported.length+' progress '+(imported.length===1?'note':'notes')+' imported from TXT.';persist();renderCards();if(window.toast)toast(imported.length+' progress '+(imported.length===1?'note':'notes')+' imported');
 }catch(e){alert('TXT import failed: '+(e&&e.message?e.message:'Unsupported file.'));}finally{input.value='';}
};

function init(){buildRows();loadStore();renderCards();$('pn-new-lot').addEventListener('keydown',e=>{if(e.key==='Enter')window.pnCreatePatient();});}
init();
})();
